export enum GameModelActionTypes {
    ADD_GOLD = 'add_gold',
    ADD_EXP = 'add_exp',
    ADD_FAME = 'add_fame',
    ASSIGN_QUEST = 'assign_quest',
    RECRUIT_HERO = 'recruit_hero',
    COMPLETE_QUEST = 'complete_quest',
    HERO_LVL_UP = 'hero_level_up',
    HERO_BULK_LVL_UP = 'hero_bulk_level_up',
    SET_IMPROVEMENT = 'set_improvement',
    TRAIN_CLICK = 'train_click',
    CLEAR_GAME_DATA = 'clear_game_data',
    START_QUEST = 'start_quest',
    END_QUEST_SUCCEED = 'end_quest_succeed',
    END_QUEST_FAIL = 'end_quest_fail',
    REPEAT_QUEST = 'repeat_quest',
    REGISTER_CFH_RESULT = 'register_cfh_result',
    EQUIP_ITEM = 'equip_item',
    REMOVE_ALL_ITEMS = 'remove_all_items',
    REMOVE_ITEM = 'remove_item',
    HERO_RANK_UP = 'hero_rank_up'
}