export enum GameModelActionTypes {
    ADD_GOLD = 'add_gold',
    ADD_EXP = 'add_exp',
    ADD_FAME = 'add_fame',
    ASSIGN_QUEST = 'assign_quest',
    SET_AUTO_QUEST = 'set_auto_quest',
    RECRUIT_HERO = 'recruit_hero',
    COMPLETE_QUEST = 'complete_quest',
    HERO_LVL_UP = 'hero_level_up',
    COMPLETE_DUNGEON = 'complete_dungeon',
    SET_IMPROVEMENT = 'set_improvement',
    TRAIN_CLICK = 'train_click',
    CLEAR_GAME_DATA = 'clear_game_data',
    START_QUEST = 'start_quest',
    END_QUEST_SUCCEED = 'end_quest_succeed',
    END_QUEST_FAIL = 'end_quest_fail',
    REGISTER_CFH_RESULT = 'register_cfh_result',
    EQUIP_ITEM = 'equip_item',
    REMOVE_ALL_ITEMS = 'remove_all_items'
}